language: php

php:
- 7.1
- 7.2

env:
  - DB=mysql
  - DB=postgres

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

before_script:
- sh -c "if [ '$DB' = 'mysql' ]; then sudo mysql -e 'use mysql; update user set authentication_string=PASSWORD('root') where user='root''; fi"
- sh -c "if [ '$DB' = 'mysql' ]; then sudo mysql -e 'use mysql;update user set plugin='mysql_native_password''; fi"
- sh -c "if [ '$DB' = 'mysql' ]; then sudo mysql -e 'use mysql;FLUSH PRIVILEGES;'; fi"
- sh -c "if [ '$DB' = 'mysql' ]; then sudo mysql_upgrade -u root -proot; fi"
- sh -c "if [ '$DB' = 'mysql' ]; then sudo mysql -u root -proot -e 'create database powerormtest;'; fi"
- sh -c "if [ '$DB' = 'mysql' ]; sudo service mysql restart; fi"
- sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'CREATE DATABASE powerormtest;' -U postgres; fi"

- composer install

script:
- vendor/phpunit/phpunit/phpunit
- vendor/phpunit/phpunit/phpunit --configuration tests/dbconfigs/phpunit_$DB.xml
