<?php
include_once("operations/Operation.php");
include_once("operations/Model.php");
include_once("operations/Field.php");
include_once("Executor.php");
include_once("Recorder.php");
include_once("Loader.php");
include_once("Questioner.php");
include_once("State.php");
include_once("AutoDetector.php");
include_once("FileHandler.php");
include_once("Graph.php");
include_once("Migration.php");