<?php

/*
* This file is part of the powerorm package.
*
* (c) Eddilbert Macharia <edd.cowan@gmail.com>
*
* For the full copyright and license information, please view the LICENSE
* file that was distributed with this source code.
*/

namespace Eddmash\PowerOrm\Model\Field;

use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Types\Type;
use Eddmash\PowerOrm\Db\ConnectionInterface;
use Eddmash\PowerOrm\Form\Widgets\TextArea;
use Eddmash\PowerOrm\Helpers\ArrayHelper;

class TextField extends Field
{
    /**
     * {@inheritdoc}
     */
    public function dbType(ConnectionInterface $connection)
    {
        return Type::TEXT;
    }

    /**
     * {@inheritdoc}
     */
    public function formField($kwargs = [])
    {
        $kwargs['max_length'] = $this->maxLength;
        $kwargs['widget'] = ArrayHelper::getValue($kwargs, 'widget', TextArea::class);

        return parent::formField($kwargs); // TODO: Change the autogenerated stub
    }
}
