<?php

/*
* This file is part of the ci306 package.
*
* (c) Eddilbert Macharia <edd.cowan@gmail.com>
*
* For the full copyright and license information, please view the LICENSE
* file that was distributed with this source code.
*/

namespace Eddmash\PowerOrm\Model\Lookup;

class Range extends BaseLookup
{
    public static $lookupName = 'range';

    public function getLookupOperation($rhs)
    {
        return parent::getLookupOperation($rhs); // TODO: Change the autogenerated stub
    }

}
