<?php

/**
 * This file is part of the powercomponents package.
 *
 * (c) Eddilbert Macharia (http://eddmash.com)<edd.cowan@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eddmash\PowerOrm\App;

use Eddmash\PowerOrm\Helpers\ArrayHelper;
use Eddmash\PowerOrm\Helpers\ClassHelper;

class Settings
{
    private $autoloadModels;
    private $modelsNamespace;
    private $migrationNamespace = 'App\Migrations';
    private $dbMappingTypes = [];
    private $dbTypes = [];
    private $dateFormats = [
        'Y-m-d',      // '2006-10-25'
        'm/d/Y',      // '10/25/2006'
        'm/d/y',     // '10/25/06'
    ];
    private $timeFormats = [
        'H:i:s',     // '14:30:59'
        'H:i:s.u',  // '14:30:59.000200'
        'H:i',        // '14:30'
    ];

    /**
     * @var SignalManagerInterface event manager to use
     */
    private $signalManager;

    /**
     * @var string command class names to add to the orm manager
     */
    protected $commands = [];

    private $timezone = '';

    /**
     * The configurations to use to connect to the database.
     *
     * It should be an array which must contain at least one of the following.
     *
     * Either 'driver' with one of the following values:
     *
     *     pdo_mysql
     *     pdo_sqlite
     *     pdo_pgsql
     *     pdo_oci (unstable)
     *     pdo_sqlsrv
     *     pdo_sqlsrv
     *     mysqli
     *     sqlanywhere
     *     sqlsrv
     *     ibm_db2 (unstable)
     *     drizzle_pdo_mysql
     *
     * OR 'driverClass' that contains the full class name (with namespace) of the
     * driver class to instantiate.
     *
     * Other (optional) parameters:
     *
     * <b>user (string)</b>:
     * The username to use when connecting.
     *
     * <b>password (string)</b>:
     * The password to use when connecting.
     *
     * <b>driverOptions (array)</b>:
     * Any additional driver-specific options for the driver. These are just passed
     * through to the driver.
     *
     * <b>pdo</b>:
     * You can pass an existing PDO instance through this parameter. The PDO
     * instance will be wrapped in a Doctrine\DBAL\Connection.
     *
     * <b>wrapperClass</b>:
     * You may specify a custom wrapper class through the 'wrapperClass'
     * parameter but this class MUST inherit from Doctrine\DBAL\Connection.
     *
     * <b>driverClass</b>:
     * The driver class to use.
     *
     * <strong>USAGE:</strong>
     *
     * [
     *       'dbname' => 'tester',
     *       'user' => 'root',
     *       'password' => 'root1.',
     *       'host' => 'localhost',
     *       'driver' => 'pdo_mysql',
     * ]
     *
     * @var array
     */
    private $database;

    /**
     * @var
     */
    private $charset = 'utf-8';

    /**
     * path from where to get and put migration files.
     *
     * @var string
     */
    private $migrationPath;

    /**
     * Path from where to get the models.
     *
     * @var string
     */
    private $modelsPath;

    /**
     * The value to prefix the database tables with.
     *
     * @var string
     */
    private $dbPrefix;

    /**
     * A list of identifiers of messages generated by the system check (e.g. ["models.W001"]) that you wish to
     * permanently acknowledge and ignore.
     *
     * Silenced warnings will no longer be output to the console;
     * silenced errors will still be printed, but will not prevent management commands from running.
     *
     * @var array
     */
    private $silencedChecks = [];

    /**
     * The namespace to check for the application models and migrations.
     *
     * @var string
     */
    private $appNamespace = 'App\\';

    private $components;

    /**
     * Settings constructor.
     *
     * @param array $configs
     *
     * @throws \Eddmash\PowerOrm\Exception\KeyError
     */
    public function __construct(array $configs)
    {
        $models = ArrayHelper::pop($configs, 'models', []);
        $migrations = ArrayHelper::pop($configs, 'migrations', []);

        $this->signalManager = ArrayHelper::pop($models, 'signalManager', null);
        $this->modelsPath = ArrayHelper::getValue($models, 'path', null);
        $this->autoloadModels = ArrayHelper::getValue($models, 'autoload', true);
        $this->modelsNamespace = ArrayHelper::getValue($models, 'namespace');
        $this->migrationPath = ArrayHelper::getValue($migrations, 'path');

        ClassHelper::setAttributes($this, $configs);
        if (!$this->components):
            $this->components = [];
        endif;
    }

    /**
     * @return mixed
     */
    public function getModelsNamespace()
    {
        return $this->modelsNamespace;
    }

    /**
     * @param mixed $modelsNamespace
     */
    public function setModelsNamespace($modelsNamespace)
    {
        $this->modelsNamespace = $modelsNamespace;
    }

    /**
     * @return string
     */
    public function getMigrationNamespace()
    {
        return $this->migrationNamespace;
    }

    /**
     * @param string $migrationNamespace
     */
    public function setMigrationNamespace($migrationNamespace)
    {
        $this->migrationNamespace = $migrationNamespace;
    }

    /**
     * @return array
     */
    public function getDbMappingTypes()
    {
        return $this->dbMappingTypes;
    }

    /**
     * @param array $dbMappingTypes
     */
    public function setDbMappingTypes($dbMappingTypes)
    {
        $this->dbMappingTypes = $dbMappingTypes;
    }

    /**
     * @return array
     */
    public function getDbTypes()
    {
        return $this->dbTypes;
    }

    /**
     * @param array $dbTypes
     */
    public function setDbTypes($dbTypes)
    {
        $this->dbTypes = $dbTypes;
    }

    /**
     * @return array
     */
    public function getDateFormats()
    {
        return $this->dateFormats;
    }

    /**
     * @param array $dateFormats
     */
    public function setDateFormats($dateFormats)
    {
        $this->dateFormats = $dateFormats;
    }

    /**
     * @return array
     */
    public function getTimeFormats()
    {
        return $this->timeFormats;
    }

    /**
     * @param array $timeFormats
     */
    public function setTimeFormats($timeFormats)
    {
        $this->timeFormats = $timeFormats;
    }

    /**
     * @return SignalManagerInterface
     */
    public function getSignalManager()
    {
        return $this->signalManager;
    }

    /**
     * @param SignalManagerInterface $signalManager
     */
    public function setSignalManager($signalManager)
    {
        $this->signalManager = $signalManager;
    }

    /**
     * @return string
     */
    public function getCommands()
    {
        return $this->commands;
    }

    /**
     * @param string $commands
     */
    public function setCommands($commands)
    {
        $this->commands = $commands;
    }

    /**
     * @return string
     */
    public function getTimezone()
    {
        return $this->timezone;
    }

    /**
     * @param string $timezone
     */
    public function setTimezone($timezone)
    {
        $this->timezone = $timezone;
    }

    /**
     * @return array
     */
    public function getDatabase()
    {
        return $this->database;
    }

    /**
     * @param array $database
     */
    public function setDatabase($database)
    {
        $this->database = $database;
    }

    /**
     * @return mixed
     */
    public function getCharset()
    {
        return $this->charset;
    }

    /**
     * @param mixed $charset
     */
    public function setCharset($charset)
    {
        $this->charset = $charset;
    }

    /**
     * @return string
     */
    public function getMigrationPath()
    {
        return $this->migrationPath;
    }

    /**
     * @param string $migrationPath
     */
    public function setMigrationPath($migrationPath)
    {
        $this->migrationPath = $migrationPath;
    }

    /**
     * @return string
     */
    public function getModelsPath()
    {
        return $this->modelsPath;
    }

    /**
     * @param string $modelsPath
     */
    public function setModelsPath($modelsPath)
    {
        $this->modelsPath = $modelsPath;
    }

    /**
     * @return string
     */
    public function getDbPrefix()
    {
        return $this->dbPrefix;
    }

    /**
     * @param string $dbPrefix
     */
    public function setDbPrefix($dbPrefix)
    {
        $this->dbPrefix = $dbPrefix;
    }

    /**
     * @return array
     */
    public function getSilencedChecks()
    {
        return $this->silencedChecks;
    }

    /**
     * @param array $silencedChecks
     */
    public function setSilencedChecks($silencedChecks)
    {
        $this->silencedChecks = $silencedChecks;
    }

    /**
     * @return string
     */
    public function getAppNamespace()
    {
        return $this->appNamespace;
    }

    /**
     * @param string $appNamespace
     */
    public function setAppNamespace($appNamespace)
    {
        $this->appNamespace = $appNamespace;
    }

    /**
     * @return mixed
     */
    public function getComponents()
    {
        return $this->components;
    }

    /**
     * @param mixed $components
     */
    public function setComponents($components)
    {
        $this->components = $components;
    }

    /**
     * @return mixed
     */
    public function getAutoloadModels()
    {
        return $this->autoloadModels;
    }

    /**
     * @param mixed $autoloadModels
     */
    public function setAutoloadModels($autoloadModels)
    {
        $this->autoloadModels = $autoloadModels;
    }
}
